# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456789012

      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: "Display message"
        run: echo "Hello, world!"

      - name: "Showing environment variables"
        #if: ${{ env.platform == 'azure' }}
        run: |
          echo "Este es el valor de platform: ${{ env.platform }}"
          echo "Este es el valor de region: ${{ env.region }}"
          echo "Este es el valor de account: ${{ env.account }}"

          echo "Este es el valor de username: ${{ env.username }}"
          echo "Este es el valor de password: ${{ env.password }}"

          echo "Project version ${{ vars.PROJECT_VERSION }}"

      - name: "Showing values only if the user is correct"
        if: ${{ env.username != '' && env.password != '' }}
        run: |
          echo "Si existe usuario y contraseña"

      - name: "Showing default variables"
        run: |
          echo "Event: ${{ toJSON(github.event) }}"
          echo "Github_ACTOR: $GITHUB_ACTOR"
          echo "Github_REPOSITORY: $GITHUB_REPOSITORY"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
